### ISSUE TITLE
references to the algorithms?

### ISSUE THREAD

**Issue by Sannndy0000** [KrishnanSG/Nutshell#1]
Hi,

Thanks a lot for making this tool!
I wonder what are the extractive summarization algorithm you use? Could you please refer me to a paper or website?

Thanks!

**Comment by KrishnanSG** [comment]
Hi @Sannndy0000,

Thanks for checking out Nutshell, motivates me a lot.

References:
1. https://www.irjet.net/archives/V6/i4/IRJET-V6I4564.pdf - This paper provides the structure to the whole idea and methodology
2. https://arxiv.org/pdf/1602.03606.pdf - provides comparison on which similarity algorithm to use and implementation for BM25 algorithm used in the library
3. https://sci-hub.do/10.1109/ICCSIT.2009.5234971 - provides good overview to the idea and useful links for further reading

Also to understand deeper about the process and working, you can read any good NLP textbook.
